* Micropore Filling

- for pores with radii less than 15 A, adsorption follows micro-pore filling rather than surface coverage cite:Bering1966
- in pores greater than 15 A, adsorption initially starts as surface coverage mechanism, but later turns into pore filling by capillary condensation mechanism once a threshold relative pressure is reached cite:Bering1966
- adsorption in micropores is a limiting case of the capillary condensation theory cite:Bering1966


* Potential Theory

- the potential theory was proposed for the characterization of sub-critical adsorption in micro-porous substances cite:Dubinin1960
- cite:Dubinin1960 found the ratio of limiting adsorption to micropore volume to be constant for many microporous substances (<0.7 nm) at different temperatures, but could not find a correlation between surface area and adsorption for these substances, thus proposing the potential theory of adsorption. 
- the Potential model does not have the correct Henry's law behaviour at low pressures cite:Do1998
- cite:Clarkson1997  showed that micropore filling was the primary adsorption mechanism in shales. 
- temperature invariance is not a requirement for potential theory but rather just a co-incidence for many substances cite:Do1998
  - temperature invariance holds as long as adsorption forces are temperature-independent dispersion forces cite:Clarkson1997
- adsorption potential is given by cite:Dubinin1960
  - $A = R T ln (P/P_0)$
- cite:Dubinin1960 found that a plot of surface coverage, $\theta = W/W_0$, against adsorption potential, A, is temperature invariant.
- micro-pore volume is often positively correlated with TOC content of shales suggesting that micropores are more prevalent in organic pores cite:Wang2016
- micropore filling occurs due to the adsorption force field encompassing the entire volume of micropores, leading to a significantly higher heat of adsorption compared to flat surfaces cite:Do1998
- a theoretical monolayer amount calculated from a Langmuir model is 2-3 times larger than the maximum associated with micropore filling cite:Do1998
- test to see if micropore filling is the prevailing adsorption mechanism cite:Clarkson2000
  - $\frac{C_{\mu 1}}{C_{\mu 2 }} ~ \frac{V_{v 1}}{V_{v 2}} \neq \frac{SSA_1}{SSA_2}$
- another way of finding out if micropore filling is the dominant adsorption mechanism is to find out if a correlation could be obtained between Langmuir volumes (max adsorbed) and micropore volumes from the D-R equation. 

* Dubinin-Astakhov Model 

- $$W = W_0 exp [-(\frac{R T}{\beta E} {ln \frac {P_0}{P}})^n]$$ 
  - where, 
  - w is amount adsorbed 
  - $w_0$ is the micropore volume 
  - $\beta$ is the affinity constant 
  - E is the characteristic energy
  - n is a fitting constant 
- The linear form of the equation is given as: 
  - $$ log(W) = log(W_0) - D(log(\frac{P_0}{P}))^n$$ 
    - where w is the amount adsorbed, 
    - w0 is the micropore volume 
    - P0 is the saturation pressure 
    - n is the Astakhov exponent

* Dubinin-Radushkevich Model

- initially proposed by cite:Dubinin1960 for subcritical vapours in microporous solids
- the DR model is a special case of the DA model where n=2, thereby reducing the number of fitting parameters
- $$W = W_0 exp [-(\frac{R T}{\beta E} {ln \frac {P_0}{P}})^2]$$ 
- where, 
  - w is amount adsorbed 
  - $w_0$ is the micropore volume 
  - $\beta$ is the affinity constant 
  - E is the characteristic energy
- in terms of number of moles: 
  - $C_{\mu}=C_{\mu s}exp[-\frac{1}{(\beta E_0)^2}(RTln(\frac{P}{P_0}))^2]$
  - where,
  - E0 is the solid characteristic energy towards a reference adsorbate - Benzene is widely used as a reference adsorbate.
  - $\beta$ is a constant which is a function of the adsorptive only.
  - Maximum adsorption capacity is the ratio of the micropore volume to the liquid molar volume: $C_{\mu s} = \frac{W_0}{v_m (T)}$

** The Characteristic Curve
- a plot of the logarithm of the amount adsorbed against the square of adsorption potential
- the slope of the characteristic curve is inverse of the square of the characteristic energy, $E=\beta*E_0$, $\sqrt(E)$
- characteristic curve, and the characteristic energy, does not change with temperature, this is not one of the assumptions of the potential theory, but merely an phenomenon that is observed to be true for many microporous carbon based adsorbents cite:Do1998
- the isosteric heat of adsorption of the DR equation can be derived from the van't Hoff's equation
  - $-\Delta H = \Delta H_{vap} + \beta E_0(ln(\frac{1}{\theta}))^{(1/2)} + \frac{(\beta E_0)\delta T}{2}(ln(\frac{1}{\theta}))^{(-1/2)}$
  - where, 
  - $\Delta H_{vap}$ is the latent heat of vaporisation.
  - $\delta$ is the change in saturation capacity with respect to temperature: $\frac{1}{C_{\mu s}} \frac{dC_{\mu s}}{dT}=-\delta$
- the net heat of adsorption is the isosteric heat minus the heat of vaporization: 
  - $-\Delta H = \beta E_0(ln(\frac{1}{\theta}))^{(1/2)} + \frac{(\beta E_0)\delta T}{2}(ln(\frac{1}{\theta}))^{(-1/2)}$
- heat of adsorption may be calculated as cite:Clarkson2000:
  - $Q=\Delta H_{vap} + \beta E$
- the enthalpy of immersion is the amount of heat released if the adsorption takes place in a bulk liquid adsorbate.
  - as adsorbate density is assumed to be equal to liquid density in absence of more accurate data, there is no phase change associated with this metric - enthalpy of immersion.
  - heat of immersion is calculated from the net heat of adsorption: 
  - $\Delta h_i = \int_0^1 q_{net} (\theta) d\theta = -(\beta E_0)(1+\delta T) \Gamma(\frac{3}{2})$
  - from experiments that determine the heat of immersion for different systems, the characteristic energy can be calculated cite:Do1998
- the DR model often provides a better fit for shale adsorption, despite having the same number of parameters as Lanmmuir cite:Clarkson1997
